name: clock-signal
version: '23.12.28'
summary: A Qt-based emulator of various 8- and 16-bit computers and consoles.
description: |
  A Qt-based emulator of the Acorn Electron, Amstrad CPC, Apple II/II+/IIe and
  early Macintosh, Atari 2600 and ST, ColecoVision, Commodore Vic-20 and Amiga,
  Enterprise 64/128, MSX 1/2, Oric 1/Atmos, early PC compatibles, Sega Master
  System, Sinclair ZX80/81 and ZX Spectrum.

grade: stable
confinement: strict
base: core18

apps:
  clock-signal:
    command: bin/desktop-launch $SNAP/opt/clksignal/bin/clksignal
    environment:
        DISABLE_WAYLAND: 1
    plugs: [x11, opengl, desktop, desktop-legacy, unity7, audio-playback, home, pulseaudio]

parts:
  clock-signal:
    source: https://github.com/TomHarte/CLK/archive/master.zip
    plugin: qmake
    qt-version: qt6
    project-files: [CLK-master/OSBindings/Qt/clksignal.pro]
    build-packages:
      - qt6-base-dev
      - libqt6gui6
      - qtmultimedia6-dev
      - libqt6x11extras6-dev
      - libqt6opengl6-dev
      - portaudio19-dev
    stage-packages:
      - libqt6gui6
      - libqt6widgets6
      - libqt6multimedia6
      - libqt6multimedia6-plugins
      - libqt6x11extras6
      - libqt6opengl6
      - libglu1-mesa
    after: [desktop-qt6]

  desktop-qt6:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt6"]
    build-packages:
      - build-essential
      - qtbase6-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt6gui6
      - libqt6x11extras6
      - libqt6opengl6
      - libgdk-pixbuf2.0-0
      - libqt6svg6 # for loading icon themes which are svg
      - try: [appmenu-qt6] # not available on core18
      - locales-all
      - xdg-user-dirs
      - fcitx-frontend-qt6

  qt6-gtk-platform:
    plugin: nil
    stage-packages:
      - qt6-gtk-platformtheme

