name: clock-signal
version: '23.12.28'
grade: stable
confinement: strict
base: core18
summary: A Qt-based emulator of various 8- and 16-bit computers and consoles.
description: |
  A Qt-based emulator of the Acorn Electron, Amstrad CPC, Apple II/II+/IIe and
  early Macintosh, Atari 2600 and ST, ColecoVision, Commodore Vic-20 and Amiga,
  Enterprise 64/128, MSX 1/2, Oric 1/Atmos, early PC compatibles, Sega Master
  System, Sinclair ZX80/81 and ZX Spectrum.

apps:
  clock-signal:
    command: bin/desktop-launch $SNAP/opt/clksignal/bin/clksignal
    extensions:
      - kde-neon
    plugs: [opengl, unity7, audio-playback, home, pulseaudio]

parts:
  clock-signal:
    source: https://github.com/TomHarte/CLK/archive/master.zip
    plugin: qmake
    qt-version: qt5
    project-files: [CLK-master/OSBindings/Qt/clksignal.pro]
    build-packages:
      - qt5-base-dev
      - libqt5gui5
      - qtmultimedia5-dev
      - libqt5x11extras5-dev
      - libqt5opengl5-dev
      - portaudio19-dev
    stage-packages:
      - libqt5gui5
      - libqt5widgets5
      - libqt5multimedia5
      - libqt5multimedia5-plugins
      - libqt5x11extras5
      - libqt5opengl5
      - libglu1-mesa
