name: clock-signal
version: '20.7.20'
summary: A Qt-based emulator of various 8- and 16-bit computers and consoles.
description: |
  A Qt-based emulator of the Acorn Electron, Amstrad CPC, Apple II/II+/IIe and
  early Macintosh, Atari 2600 and ST, ColecoVision, Commodore Vic-20,
  MSX 1, Oric 1/Atmos, Sega Master System and Sinclair ZX80/81.

grade: devel
confinement: strict
base: core18

apps:
  clock-signal:
    command: bin/desktop-launch $SNAP/opt/ClockSignal/bin/ClockSignal
    plugs: [x11, opengl, desktop, home, audio-playback]
#     environment:
#       # Use GTK3 cursor theme, icon theme and open/save file dialogs.
#       QT_QPA_PLATFORMTHEME: gtk3

parts:
  clock-signal:
    source: https://github.com/TomHarte/CLK/archive/master.zip
    plugin: qmake
    qt-version: qt5
    project-files: [CLK-master/OSBindings/Qt/ClockSignal.pro]
    build-packages:
      - libqt5core5a
      - libqt5gui5
      - qtmultimedia5-dev
    stage-packages:
      - libqt5gui5
      - libqt5widgets5
      - libqt5multimedia5
    after: [desktop-qt5]

# From here downward is as advocated by https://forum.snapcraft.io/t/desktop-app-support-qt5/11703

  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - build-essential
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - try: [appmenu-qt5] # not available on core18
      - locales-all
      - xdg-user-dirs
      - fcitx-frontend-qt5
      - libgtk2.0-0

#   qt5-gtk-platform:
#     plugin: nil
#     stage-packages:
#       - qt5-gtk-platformtheme

# plugs:
#   # Support for common GTK themes
#   # https://forum.snapcraft.io/t/how-to-use-the-system-gtk-theme-via-the-gtk-common-themes-snap/6235
#   gsettings:
#   gtk-3-themes:
#     interface: content
#     target: $SNAP/data-dir/themes
#     default-provider: gtk-common-themes
#   icon-themes:
#     interface: content
#     target: $SNAP/data-dir/icons
#     default-provider: gtk-common-themes
#   sound-themes:
#     interface: content
#     target: $SNAP/data-dir/sounds
#     default-provider: gtk-common-themes
