name: clock-signal
confinement: strict
grade: stable
base: core24
version: '2025-12-18'
summary: A Qt-based emulator of various 8- and 16-bit computers and consoles.
description: |
  A Qt-based emulator of the Acorn Electron, BBC Micro and Archimedes, Amstrad CPC,
  Apple II/II+/IIe, early Apple Macintosh, Atari 2600, Atari ST, ColecoVision,
  Commodore Vic-20, Plus 4 and Amiga, Enterprise 64/128, MSX 1/2, Oric 1/Atmos,
  early PC compatibles, Sega Master System, Sinclair ZX80/ZX81 and ZX Spectrum.

# kf6-core24-sdk appears to exist only for amd64 and arm64; this platform restriction
# is implied by this project's dependencies.
platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]

apps:
  clock-signal:
    command: usr/local/bin/clksignal
    extensions: [kde-neon-6]
    plugs:
      - home
      - removable-media
      - pulseaudio
      - screen-inhibit-control
      - joystick

package-repositories:
  - type: apt
    url: http://origin.archive.neon.kde.org/user
    suites: [noble]
    components: [main]
    architectures: [amd64, arm64]
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D

parts:
  clock-signal:
    plugin: cmake
    source: https://github.com/TomHarte/CLK.git
    source-tag: $SNAPCRAFT_PROJECT_VERSION
    cmake-parameters:
      - -DCLK_UI=Qt
      - -DCMAKE_BUILD_TYPE=Release
    build-packages:
      - zlib1g-dev
      - libpulse-dev
      - libxkbcommon-dev
      - libduktape207
